version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # environment:
      # - CHOKIDAR=USE_POLLING
    restart: always
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopassword
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopassword@mongo:27017/
    depends_on:
      - mongo


volumes:
  mongodb_data: